#!/usr/bin/env bash
# Report disk usage on a GitHub Actions runner and estimate reclaimable space.
#
# Usage:
#   ./scripts/ci-disk-inventory.sh [stage-name]
#
# Writes human-readable output to stdout and, when GITHUB_STEP_SUMMARY is set,
# appends a markdown section for the given stage.

set -euo pipefail

STAGE="${1:-inventory}"
REPORT="${GITHUB_STEP_SUMMARY:-}"

human_size() {
    local bytes="$1"
    if command -v numfmt >/dev/null 2>&1; then
        numfmt --to=iec-i --suffix=B "$bytes" 2>/dev/null || echo "${bytes}B"
    else
        echo "${bytes}B"
    fi
}

dir_bytes() {
    local path="$1"
    if [[ -e "$path" ]]; then
        du -sb "$path" 2>/dev/null | awk '{print $1}'
    else
        echo 0
    fi
}

TOTAL_RECLAIMABLE=0

report_candidate() {
    local label="$1"
    local path="$2"
    local note="${3:-}"
    local bytes size

    if [[ ! -e "$path" ]]; then
        printf '  %-42s %10s  %s\n' "$label" '-' "(missing)"
        markdown_row "$label" "-" "missing"
        return
    fi

    bytes="$(dir_bytes "$path")"
    size="$(human_size "$bytes")"
    if [[ -n "$note" ]]; then
        printf '  %-42s %10s  %s\n' "$label" "$size" "$note"
    else
        printf '  %-42s %10s\n' "$label" "$size"
    fi
    markdown_row "$label" "$size" "$note"
    TOTAL_RECLAIMABLE=$((TOTAL_RECLAIMABLE + bytes))
}

section() {
    local title="$1"
    echo ""
    echo "=== ${title} ==="
    if [[ -n "$REPORT" ]]; then
        {
            echo ""
            echo "## ${title}"
            echo ""
        } >>"$REPORT"
    fi
}

markdown_table_header() {
    if [[ -n "$REPORT" ]]; then
        {
            echo "| Candidate | Size | Notes |"
            echo "|-----------|------|-------|"
        } >>"$REPORT"
    fi
}

markdown_row() {
    local label="$1"
    local size="$2"
    local note="${3:-}"

    if [[ -n "$REPORT" ]]; then
        echo "| ${label} | ${size} | ${note} |" >>"$REPORT"
    fi
}

echo "disk inventory stage: ${STAGE}"
echo "timestamp: $(date -u +%Y-%m-%dT%H:%M:%SZ)"

if [[ -n "$REPORT" ]]; then
    {
        echo ""
        echo "# Disk inventory — ${STAGE}"
        echo ""
        echo "_UTC $(date -u +%Y-%m-%dT%H:%M:%SZ)_"
        echo ""
    } >>"$REPORT"
fi

section "Filesystem summary"
echo ""
df -h / /tmp "${RUNNER_TEMP:-/home/runner/work/_temp}" 2>/dev/null || df -h
if [[ -n "$REPORT" ]]; then
    {
        echo '```'
        df -h / /tmp "${RUNNER_TEMP:-/home/runner/work/_temp}" 2>/dev/null || df -h
        echo '```'
    } >>"$REPORT"
fi

section "Preinstalled runner tooling (typical cleanup targets)"
markdown_table_header
printf '  %-42s %10s  %s\n' "CANDIDATE" "SIZE" "NOTES"
printf '  %-42s %10s  %s\n' "--------" "----" "-----"

report_candidate "Android SDK" "/usr/local/lib/android" "largest common win on ubuntu-latest"
report_candidate ".NET SDK" "/usr/share/dotnet"
report_candidate "GHC (Haskell)" "/opt/ghc"
report_candidate "Hosted tool cache" "/opt/hostedtoolcache" "Node/Python/Ruby/Go runtimes"
report_candidate "PowerShell" "/usr/local/share/powershell"
report_candidate "Chromium" "/usr/local/share/chromium"
report_candidate "Swift" "/usr/share/swift"
if [[ -d /usr/local ]]; then
    for julia_dir in /usr/local/julia*; do
        [[ -d "$julia_dir" ]] || continue
        report_candidate "Julia ($(basename "$julia_dir"))" "$julia_dir"
    done
fi
report_candidate "GHCup" "/usr/local/.ghcup"
report_candidate "Az CLI modules" "/opt/az"
report_candidate "CodeQL toolcache" "/opt/hostedtoolcache/CodeQL" "subset of toolcache"
report_candidate "Java toolcache" "/opt/hostedtoolcache/Java" "subset of toolcache"

section "Package manager and temp data"
markdown_table_header
printf '  %-42s %10s  %s\n' "CANDIDATE" "SIZE" "NOTES"
printf '  %-42s %10s  %s\n' "--------" "----" "-----"

report_candidate "APT archives" "/var/cache/apt/archives" "apt-get clean"
report_candidate "APT lists" "/var/lib/apt/lists" "regenerated by apt-get update"
report_candidate "/tmp" "/tmp" "ephemeral; safe if nothing running"
report_candidate "Runner temp" "${RUNNER_TEMP:-/home/runner/work/_temp}"

section "Docker"
if command -v docker >/dev/null 2>&1; then
    echo ""
    docker system df -v 2>/dev/null || docker system df || true
    if [[ -n "$REPORT" ]]; then
        {
            echo '```'
            docker system df 2>/dev/null || true
            echo '```'
        } >>"$REPORT"
    fi

    echo ""
    echo "Docker images:"
    docker images --format 'table {{.Repository}}\t{{.Tag}}\t{{.Size}}' 2>/dev/null || true
else
    echo "docker: not available"
fi

section "Workspace checkout"
markdown_table_header
printf '  %-42s %10s  %s\n' "CANDIDATE" "SIZE" "NOTES"
printf '  %-42s %10s  %s\n' "--------" "----" "-----"

if [[ -n "${GITHUB_WORKSPACE:-}" && -d "$GITHUB_WORKSPACE" ]]; then
    report_candidate "GITHUB_WORKSPACE" "$GITHUB_WORKSPACE"
    if [[ -d "$GITHUB_WORKSPACE/node-pipeline" ]]; then
        report_candidate "node-pipeline checkout" "$GITHUB_WORKSPACE/node-pipeline"
    fi
    for node_dir in "$GITHUB_WORKSPACE"/node*; do
        [[ -d "$node_dir" ]] || continue
        [[ "$(basename "$node_dir")" == node-pipeline ]] && continue
        report_candidate "$(basename "$node_dir") checkout" "$node_dir"
    done
    if [[ -d "$GITHUB_WORKSPACE/node-pipeline/dist" ]]; then
        report_candidate "built debs (dist/)" "$GITHUB_WORKSPACE/node-pipeline/dist"
    fi
else
    echo "  GITHUB_WORKSPACE not set or missing"
fi

section "Estimated reclaimable (listed candidates only)"
ESTIMATED="$(human_size "$TOTAL_RECLAIMABLE")"
echo ""
echo "Sum of existing cleanup candidates above: ${ESTIMATED}"
echo "(Docker reclaimable space is reported separately by 'docker system df'.)"
echo "(Toolcache subsets overlap their parent; treat the sum as an upper bound.)"
echo ""
echo "Free space now:"
df -h / | tail -1

if [[ -n "$REPORT" ]]; then
    {
        echo ""
        echo "**Sum of listed cleanup candidates:** ${ESTIMATED}"
        echo ""
        echo "Docker reclaimable space is listed separately above. Toolcache"
        echo "subtree sizes overlap their parent — treat the sum as an upper bound."
        echo ""
        echo "**Free on /** $(df -h / | tail -1 | awk '{print $4 " available (" $5 " used)"}')"
    } >>"$REPORT"
fi
